### ISSUE TITLE
Create Skeleton File for CSR sparse matrix class

### ISSUE THREAD

**Issue by deanrp2** [bkochuna/ners570f20-Lab06#13]
The issue is about creating the header and source file for the CSR sparse matrix class

Some tasks in this issue:
* Create the header file
* Create the source file
* Define all attributes
* Create all methods as empty operations
* Create a unit test executable for this class

This issue is defined as done if the source file, header file, and unit test main are added to the repository in the correct location.

**Comment by bkochuna** [comment]
@deanrp2 and @littlewatkins Issue description looks good.

Only comment is I prefer to format the definition of done like:
> **Definition of Done**
> The source file, header file, and unit test main are added to the repository in the correct location

Could also leave the attributes to the implementation in #34 but as things are written there is a clear coordination.
The other thing I guess worth pointing out is that github does not support issue dependencies--which stinks.

You have to track it manually, but the following issues depend on the completion of this issue:
#19, #33, #34, and #32

That is all the other issues in the [Develop CSR Format](https://github.com/bkochuna/ners570f20-Lab06/milestone/5) milestone.
