### ISSUE TITLE
Add CSR Sparse Matrix Class to build system

### ISSUE THREAD

**Issue by deanrp2** [bkochuna/ners570f20-Lab06#19]
This issue about adding the CSR sparse matrix class to the CMakelists.txt file so that when the project is configured and built. This associated source and test file are compiled.

Definition of Done
The source and header file compile.

**Comment by bkochuna** [comment]
@deanrp2 Definition of done is clear. 👍

**Comment by knbarton** [comment]
I may have gotten a little carried away while working on the CSR skeleton files issue and I already added everything to the cmake files (I was trying to make sure everything worked and completely forgot compiling is a separate issue). I will just add you as a reviewer @littlewatkins so you can have some input.

**Comment by littlewatkins** [comment]
It looks good to me. Thanks for hammering this all out!
