### ISSUE TITLE
Write Tests for COO Sparse Matrix Class

### ISSUE THREAD

**Issue by peareric** [bkochuna/ners570f20-Lab06#20]
Implement a test file that constructs a COO sparse matrix class, runs each member function of the class, and asserts that functionality is correct.

**Definition of Done**
All source code in COO sparse matrix is exercised in unit tests.

**Comment by bkochuna** [comment]
Good description @peareric. Notionally, this covers everything a unit test should do.

A few suggestions to enhancing clarity though.
- You could say that the test should also check for bad inputs, errors, or other things related to misuse of the object--in addition to correct functionality.
- You could further clarify that the test should be written for single and double precision.
- You could further clarify that the test passes in the CI--or if doing test driven development that #29 passes the CI.

In some sense, these things could be reasonably assumed. But with software, I've found in my experience that the more explicit you can be, the better the resulting code is.

**Comment by mduschenes** [comment]
Added test file testCOOSparseMatrix.cpp in test directory
WIP Configure CMake correctly to compile COO test file.

**Comment by mduschenes** [comment]
Closing after pull request #65 successful
