### ISSUE TITLE
Add COO Sparse Matrix Class to build system

### ISSUE THREAD

**Issue by knbarton** [bkochuna/ners570f20-Lab06#27]
This issue about adding the COO sparse matrix class to the CMakelists.txt file so that when the project is configured and built. This associated source and test file are compiled.

**Definition of Done**
The source and header file compile.

**Comment by bkochuna** [comment]
@knbarton Good. Clear. Concise.

My only recommendation is that you might clarify/add in the definition of done that the CI passes. In some sense though this could be assumed.

**Comment by peareric** [comment]
Closed via #62
