### ISSUE TITLE
Document COO Sparse Matrix Class

### ISSUE THREAD

**Issue by hpleei** [bkochuna/ners570f20-Lab06#30]
This issue is about documenting the COO Sparse Matrix Class.

Some tasks in this issue:

- Describe attributes
- For each method in the class:
Provide a summary of what the method does
Describe inputs, outputs, (possibly any assumptions)

**Definition of Done**
A .txt file is provided as documentation for the class and/or the corresponding header files are well-documented as per the instructions above.

**Comment by bkochuna** [comment]
So, I made a similar comment to #32 that this issue will depend on establishing documentation standards and guidelines which was created in #38.

#38 should be completed before this ticket is completed.

I also recommend (as I did in #32) that the definition of done be updated based on #38.

I think what you have as some of the tasks are a great starting point though.

**Comment by peareric** [comment]
See my comment describing documentation standards in #38. Closed via #67.
