### ISSUE TITLE
Decide on infrastructure tools

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f20-Lab06#4]
The infrastructure tools to be decided upon by the team are the configure and build system (e.g. autotools, CMake, raw makefiles, etc.), and testing infrastructure (what tools will you use to define and execute tests), what systems or services will you use for running the tests.

**Comment by bkochuna** [comment]
@littlewatkins no experience. So whichever is easier and more straightfoward. This was echoed by @elmullin94 and @NuclearEngideer

**Comment by bkochuna** [comment]
@deanrp2 could write a shell script that does it all to keep it simple.

**Comment by littlewatkins** [comment]
I vote CMake

**Comment by bkochuna** [comment]
CMake is in vogue, so we'll go with that.
